version: '2'
services:
  app:
    build:
      context: .
    deploy:
      replicas: ${REPLICAS-1}
    links:
      - db
    command: npm run dev
    volumes:
      - .:/home/node/app
    environment:
      - PORT=3333
      - DB_HOST=db
      - DB_NAME=mockfsbid
      - DB_USER=mockfsbid-user
      - DB_PASSWORD=fsbid_pwd
      - DB_PORT=5432
      - DB_CHARSET=utf8
      - DB_CLIENT=postgres
      - ORACLE_USER=talentmap1
      - ORACLE_PW=talentmap1
      - ORACLE_HOST=host.docker.internal:1521/oraclepdb
      - DEBUG=false
  haproxy:
    image: eeacms/haproxy
    depends_on:
    - app
    ports:
    - "3333:5000"
    - "1937:1936"
    environment:
      BACKENDS: "app"
      BACKENDS_PORT: "3333"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
  db:
    image: postgres:13.4-alpine
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mockfsbid
      - POSTGRES_USER=mockfsbid-user
      - POSTGRES_PASSWORD=fsbid_pwd
volumes:
  pgdata:
