name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      action "Executing remote ssh commands" {
        - uses = "appleboy/ssh-action@master"
        secrets = [
          "HOST",
          "PORT",
          "USERNAME",
          "PASSWORD",
          "KEY",
          "SCRIPT"
        ]
        args = []
      }
