name: Deploy

on: 
  push:
    branches:
      - master

deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@v0.0.2
      with:
        args: > 
          --host ${{ HOST }} --user ${{ USERNAME }}
          --script 'whoami'  
