on:
  pull_request_review:
    branches-ignore:
      - 'dependabot/*'
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Approved :heavy_check_mark:"
        REMOVE_LABEL: "Approved%20Pending%20Feedback%20:stopwatch:"
